sed -i '' 's/--da-text-main: #1f2937;/--da-text-main: #333333;/' content.css
sed -i '' 's/--da-text-sub: #6b7280;/--da-text-sub: #666666;/' content.css
sed -i '' 's/--da-text-soft: #4b5563;/--da-text-soft: #888888;/' content.css
sed -i '' 's/--da-border-main: #f1d7bf;/--da-border-main: #e0e0e0;/' content.css
sed -i '' 's/--da-border-soft: #f4e2d2;/--da-border-soft: #ebebeb;/' content.css
sed -i '' 's/--da-border-input: #ecd5c0;/--da-border-input: #cccccc;/' content.css
sed -i '' 's/--da-border-strong: #e5c8af;/--da-border-strong: #b3b3b3;/' content.css
sed -i '' 's/--da-panel-bg:.*--da-head-bg/--da-panel-bg: #f9f9f9;\n  --da-head-bg/g' content.css
sed -i '' 's/--da-head-bg:.*/--da-head-bg: #f4f4f4;/' content.css
sed -i '' 's/--da-surface: #ffffff;/--da-surface: #ffffff;/' content.css
sed -i '' 's/--da-surface-soft: #fff9f3;/--da-surface-soft: #fafafa;/' content.css
sed -i '' 's/--da-primary-1: #f97316;/--da-primary-1: #f2931e;/' content.css
sed -i '' 's/--da-primary-2: #ea580c;/--da-primary-2: #e07b10;/' content.css
sed -i '' 's/--da-primary-text: #ffffff;/--da-primary-text: #ffffff;/' content.css
sed -i '' 's/--da-user-msg-border: #f6bf8f;/--da-user-msg-border: transparent;/' content.css
sed -i '' 's/--da-user-msg-bg: linear-gradient.*/--da-user-msg-bg: #fff0df;/' content.css
sed -i '' 's/--da-empty-bg: #fffdf9;/--da-empty-bg: #ffffff;/' content.css
sed -i '' 's/--da-empty-border: #f3d6bb;/--da-empty-border: #e0e0e0;/' content.css
sed -i '' 's/--da-meta-text: #6b7280;/--da-meta-text: #999999;/' content.css
sed -i '' 's/--da-secondary-btn-border: #e5c8af;/--da-secondary-btn-border: #cccccc;/' content.css
sed -i '' 's/--da-secondary-btn-bg: #ffffff;/--da-secondary-btn-bg: #ffffff;/' content.css
sed -i '' 's/--da-secondary-btn-text: #7c4a22;/--da-secondary-btn-text: #333333;/' content.css
